import Image from "next/image";
import type { Metadata } from "next";
import "./globals.css";
import Link from 'next/link';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Book Journal</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=frame_inspect" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=optional"
          rel="stylesheet"
        />
      </head>
      <body>
        <div className="container">
          <div className="main-section">
            <nav className="main-nav">
              <div className="nav-container">
                <div className="nav-logo">
                  <Image src="/images/logo.png" alt="Pleria Logo" width={118} height={32} />
                </div>
                <ul className="nav-links">
                  <li><Link href="/">Home</Link></li>
                  <li><Link href="/books">Books</Link></li>
                  <li><Link href="/readers">Readers</Link></li>
                  <li><Link href="/about">About</Link></li>
                </ul>
              </div>
            </nav>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
